module.exports = function(app) {
    var naissance = require('../service/naissanceService')

    app.route('/naissance')
        .get(naissance.getNaissance)
        .post(naissance.addNaissance)
    app.route('/naissance/:num_ordre')
        .put(naissance.updateNaissance)
        .delete(naissance.deleteNaissance)
    app.route('/naissance/get/auto_increment')
        .get(naissance.auto_increment_num_ordre)
    app.route('/naissance/getNumOrdreNaissance')
        .get(naissance.getNumOrdreNaissance)
    app.route('/naissance/getNumOrdreNaissanceDefunt')
        .get(naissance.getNumOrdreNaissanceDefunt)
    app.route('/naissance/getDataByNum_ordre/:num_ordre')
        .get(naissance.getDataByNum_ordreNaissance)
    app.route('/naissance/getOnlyDate')
        .get(naissance.getOnlyDate)
    app.route('/naissance/getTotalNombreNaissance')
        .get(naissance.getTotalNombreNaissance)
    app.route('/naissance/getPere')
        .get(naissance.getPere)
    app.route('/naissance/getMere')
        .get(naissance.getMere)
    app.route('/naissance/getDataPere/:nom_pere_enfant')
        .get(naissance.dataPere)
    app.route('/naissance/getDataMere/:nom_mere_enfant')
        .get(naissance.dataMere)
    app.route('/naissance/getDeclarantNaissance')
        .get(naissance.getDeclarantNaissance)
    app.route('/naissance/getDatDeclarant/:nom_declarant_naissance')
        .get(naissance.getDataDeclarant)

}